apiVersion: v1
kind: Service
metadata:
  name: ingress-server-service
  namespace: bill-test
spec:
  selector:
    app: ingress-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
